name: Deploy API to EC2 development instance

on:
  push:
    branches:
      - development

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create deployment package
        run: |
          mkdir -p deploy
          cp -r api deploy/
          cp -r api/package.json deploy/
          cp -r nx.json deploy/
          cp -r tsconfig.base.json deploy/

      - name: Copy deploy folder to EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_EC2_DEV_SECRET_KEY }}
          HOSTNAME: ${{secrets.AWS_EC2_DEV_HOST}}
          USER_NAME: ${{secrets.AWS_EC2_DEV_USER}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key -r ./deploy/* ${USER_NAME}@${HOSTNAME}:/home/ubuntu/app

      - name: Run docker-compose
        env:
          PRIVATE_KEY: ${{ secrets.AWS_EC2_DEV_SECRET_KEY }}
          HOSTNAME: ${{secrets.AWS_EC2_DEV_HOST}}
          USER_NAME: ${{secrets.AWS_EC2_DEV_USER}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              cd /home/ubuntu/app &&
              docker compose -f docker-compose.yml up -d --build
              '
